project:
  type: website

website:
  title: "Quarto-markdown"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: syntax/index.qmd
        text: Syntax
      - href: writers/index.qmd
        text: Writers
      - href: source-info/index.qmd
        text: Source Tracking

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



